# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the Nanosic 8030 keyboard driver.
#

obj-$(CONFIG_KEYBOARD_NANO_8030) += nanosic_driver.o
nanosic_driver-y += nano_chardev.o nano_sysfs.o nano_workqueue.o nano_driver.o \
			nano_i2c.o nano_input.o nano_timer.o nano_gpio.o nano_cache.o \
			nano_pm.o
